services:
  backend:
    build:
      context: ./
    
    container_name: news-bias-backend
    ports:
      - "5001:5000"
    
    # ensure /tmp/uv-cache is a brand-new in-memory dir
    tmpfs:
      - /tmp/uv-cache:mode=1777

    env_file:
      - ./.env 

    networks:
      - nginx-proxy-manager_nginxproxyman

networks:
  nginx-proxy-manager_nginxproxyman:
    external: true