name: Daily News Scraper

on:
  schedule:
    - cron: "30 3 * * *" # Runs at 9:00 AM IST (03:30 UTC) every day
  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install newspaper3k
          pip install nltk

      - name: Run news scraper
        run: |
          python backend/download_resources.py
          python backend/webscapper.py
